### ISSUE TITLE
views as resources; also, views from change sets interpreted as tables when describing tables

### ISSUE THREAD

**Issue by uladkasach** [uladkasach/schema-control#13]
we need to be able to support views as resources.

but also:
```
Error: Errors on 1 properties were found while validating properties for model ResourceDefinition.:
[
  {
    "message": "/"sql/" is required",
    "path": "sql",
    "type": "any.required"
  }
]
Props Provided:
{
  "name": "view_participant_current",
  "type": "TABLE"
}
    at new SchematicJoiModel (/var/www/git/Tugether/service-plans/node_modules/schematic-joi-model/dist/model.js:19:19)
    at new ResourceDefinition (/var/www/git/Tugether/service-plans/node_modules/schema-control/dist/types/objects/ResourceDefinition.js:16:1)
    at Object.<anonymous> (/var/www/git/Tugether/service-plans/node_modules/schema-control/dist/logic/definitions/_utils/getResourceFromDatabase/getResourceFromDatabase.js:30:16)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/git/Tugether/service-plans/node_modules/schema-control/dist/logic/definitions/_utils/getResourceFromDatabase/getResourceFromDatabase.js:5:58)
    at <anonymous>
```

**Comment by uladkasach** [comment]
note: the main blocker so far has been that mysql does not store any formatting for views, like it does for functions and procedures. It also does not have a human readable formatting like it does for tables.

maybe we should just apply our own formatter onto both the live sql and the user's sql and diff off of that.

**Comment by uladkasach** [comment]
duplicate of https://github.com/uladkasach/schema-control/issues/10
